### ISSUE TITLE
Structure spawning issue

### ISSUE THREAD

**Issue by Sixdd6** [jtorleonstudios/HUB-Awesome-Dungeon-Ocean#2]
Some ocean structures are spawning too high causing raised areas of water. This can be problematic for traveling by boat as if you hit one of these areas you'll sink.

mod version: 1.18.2-3.0.0

**Comment by GreyMamoN** [comment]
Dangeon spawns 7 blocks above sea level

**Comment by jtorleonstudios** [comment]
Will be fixed in the next update, thanks you for your report

**Comment by jtorleonstudios** [comment]
fixed in 3.2.0, the structures do not contain water if they are above sea level
